### ISSUE TITLE
Finish locale-selector

### ISSUE THREAD

**Issue by weotch** [BKWLD/cloak-i18n#2]
I just stubbed this out, it needs to be an actual selector.  Ideally with SVG icon support too.

- [x] Render text through localization files
- [x] Render basic button
- [x] Implement simple dropdown component like on P&B
- [x] Render list of options
- [x] Add flags
- [x] Make clicks current locale when closed open the menu
- [x] Add pattern of style overrides (see https://github.com/BKWLD/cloak-customer/issues/10#issuecomment-1091964739)

**Comment by weotch** [comment]
Here's a [design from Owlet](![image](https://user-images.githubusercontent.com/77567/163606858-9436e591-4559-4cec-8d1e-f6278bcae7f2.png))

![image](https://user-images.githubusercontent.com/77567/163606819-e559eda1-ea2e-4e74-8cdc-139fe2231792.png)
![image](https://user-images.githubusercontent.com/77567/163606812-972681a8-b138-462f-a3a9-408198507195.png)

@brokenhd , the short codes within each country link to different sites, right?  

@iamethanmartin do you think this is a good model for locale selectors moving forward?

**Comment by brokenhd** [comment]
Yes, the shortcodes link to the different language sites

**Comment by weotch** [comment]
@brokenhd I built something similar to the design, something I think is more scalable

![image](https://user-images.githubusercontent.com/77567/163686600-ef14fa8a-324f-439d-b61f-e271b03c6e61.png)

You can demo it here: https://cloak-i18n.netlify.app/

Let's review it together next week; I'm hoping the design can be a little flexible and we can implement the `layout-switcher` from this package pretty directly.
